# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: danmaku.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rdanmaku.proto\x12\x10\x62ilibili.danmaku\"Q\n\rSegmentConfig\x12\x15\n\x08\x64uration\x18\x01 \x01(\x03H\x00\x88\x01\x01\x12\x12\n\x05total\x18\x02 \x01(\x03H\x01\x88\x01\x01\x42\x0b\n\t_durationB\x08\n\x06_total\"\x84\x01\n\x0b\x44\x61nmakuInfo\x12\x12\n\x05state\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x31\n\x03seg\x18\x04 \x01(\x0b\x32\x1f.bilibili.danmaku.SegmentConfigH\x01\x88\x01\x01\x12\x12\n\x05\x63ount\x18\x08 \x01(\x03H\x02\x88\x01\x01\x42\x08\n\x06_stateB\x06\n\x04_segB\x08\n\x06_count\"T\n\x06\x42ullet\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x10\n\x08progress\x18\x02 \x01(\x05\x12\x0c\n\x04mode\x18\x03 \x01(\x05\x12\r\n\x05\x63olor\x18\x05 \x01(\r\x12\x0f\n\x07\x63ontent\x18\x07 \x01(\t\"7\n\x0b\x44\x61nmakuData\x12(\n\x06\x62ullet\x18\x01 \x03(\x0b\x32\x18.bilibili.danmaku.Bulletb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'danmaku_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SEGMENTCONFIG._serialized_start=35
  _SEGMENTCONFIG._serialized_end=116
  _DANMAKUINFO._serialized_start=119
  _DANMAKUINFO._serialized_end=251
  _BULLET._serialized_start=253
  _BULLET._serialized_end=337
  _DANMAKUDATA._serialized_start=339
  _DANMAKUDATA._serialized_end=394
# @@protoc_insertion_point(module_scope)
