# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: danmaku.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
  name='danmaku.proto',
  package='bilibili.danmaku',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rdanmaku.proto\x12\x10\x62ilibili.danmaku\"Q\n\rSegmentConfig\x12\x15\n\x08\x64uration\x18\x01 \x01(\x03H\x00\x88\x01\x01\x12\x12\n\x05total\x18\x02 \x01(\x03H\x01\x88\x01\x01\x42\x0b\n\t_durationB\x08\n\x06_total\"\x84\x01\n\x0b\x44\x61nmakuInfo\x12\x12\n\x05state\x18\x01 \x01(\x05H\x00\x88\x01\x01\x12\x31\n\x03seg\x18\x04 \x01(\x0b\x32\x1f.bilibili.danmaku.SegmentConfigH\x01\x88\x01\x01\x12\x12\n\x05\x63ount\x18\x08 \x01(\x03H\x02\x88\x01\x01\x42\x08\n\x06_stateB\x06\n\x04_segB\x08\n\x06_count\"H\n\x06\x42ullet\x12\x10\n\x08progress\x18\x02 \x01(\x05\x12\x0c\n\x04mode\x18\x03 \x01(\x05\x12\r\n\x05\x63olor\x18\x05 \x01(\r\x12\x0f\n\x07\x63ontent\x18\x07 \x01(\t\"7\n\x0b\x44\x61nmakuData\x12(\n\x06\x62ullet\x18\x01 \x03(\x0b\x32\x18.bilibili.danmaku.Bulletb\x06proto3'
)

_SEGMENTCONFIG = _descriptor.Descriptor(
  name='SegmentConfig',
  full_name='bilibili.danmaku.SegmentConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='duration', full_name='bilibili.danmaku.SegmentConfig.duration', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='total', full_name='bilibili.danmaku.SegmentConfig.total', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_duration', full_name='bilibili.danmaku.SegmentConfig._duration',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
      fields=[]),
    _descriptor.OneofDescriptor(
      name='_total', full_name='bilibili.danmaku.SegmentConfig._total',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
      fields=[]),
  ],
  serialized_start=35,
  serialized_end=116,
)

_DANMAKUINFO = _descriptor.Descriptor(
  name='DanmakuInfo',
  full_name='bilibili.danmaku.DanmakuInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='bilibili.danmaku.DanmakuInfo.state', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='seg', full_name='bilibili.danmaku.DanmakuInfo.seg', index=1,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='count', full_name='bilibili.danmaku.DanmakuInfo.count', index=2,
      number=8, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_state', full_name='bilibili.danmaku.DanmakuInfo._state',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
      fields=[]),
    _descriptor.OneofDescriptor(
      name='_seg', full_name='bilibili.danmaku.DanmakuInfo._seg',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
      fields=[]),
    _descriptor.OneofDescriptor(
      name='_count', full_name='bilibili.danmaku.DanmakuInfo._count',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
      fields=[]),
  ],
  serialized_start=119,
  serialized_end=251,
)

_BULLET = _descriptor.Descriptor(
  name='Bullet',
  full_name='bilibili.danmaku.Bullet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='progress', full_name='bilibili.danmaku.Bullet.progress', index=0,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mode', full_name='bilibili.danmaku.Bullet.mode', index=1,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='color', full_name='bilibili.danmaku.Bullet.color', index=2,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='content', full_name='bilibili.danmaku.Bullet.content', index=3,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=253,
  serialized_end=325,
)

_DANMAKUDATA = _descriptor.Descriptor(
  name='DanmakuData',
  full_name='bilibili.danmaku.DanmakuData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='bullet', full_name='bilibili.danmaku.DanmakuData.bullet', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=327,
  serialized_end=382,
)

_SEGMENTCONFIG.oneofs_by_name['_duration'].fields.append(
  _SEGMENTCONFIG.fields_by_name['duration'])
_SEGMENTCONFIG.fields_by_name['duration'].containing_oneof = _SEGMENTCONFIG.oneofs_by_name['_duration']
_SEGMENTCONFIG.oneofs_by_name['_total'].fields.append(
  _SEGMENTCONFIG.fields_by_name['total'])
_SEGMENTCONFIG.fields_by_name['total'].containing_oneof = _SEGMENTCONFIG.oneofs_by_name['_total']
_DANMAKUINFO.fields_by_name['seg'].message_type = _SEGMENTCONFIG
_DANMAKUINFO.oneofs_by_name['_state'].fields.append(
  _DANMAKUINFO.fields_by_name['state'])
_DANMAKUINFO.fields_by_name['state'].containing_oneof = _DANMAKUINFO.oneofs_by_name['_state']
_DANMAKUINFO.oneofs_by_name['_seg'].fields.append(
  _DANMAKUINFO.fields_by_name['seg'])
_DANMAKUINFO.fields_by_name['seg'].containing_oneof = _DANMAKUINFO.oneofs_by_name['_seg']
_DANMAKUINFO.oneofs_by_name['_count'].fields.append(
  _DANMAKUINFO.fields_by_name['count'])
_DANMAKUINFO.fields_by_name['count'].containing_oneof = _DANMAKUINFO.oneofs_by_name['_count']
_DANMAKUDATA.fields_by_name['bullet'].message_type = _BULLET
DESCRIPTOR.message_types_by_name['SegmentConfig'] = _SEGMENTCONFIG
DESCRIPTOR.message_types_by_name['DanmakuInfo'] = _DANMAKUINFO
DESCRIPTOR.message_types_by_name['Bullet'] = _BULLET
DESCRIPTOR.message_types_by_name['DanmakuData'] = _DANMAKUDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SegmentConfig = _reflection.GeneratedProtocolMessageType('SegmentConfig', (_message.Message,), {
  'DESCRIPTOR': _SEGMENTCONFIG,
  '__module__': 'danmaku_pb2'
  # @@protoc_insertion_point(class_scope:bilibili.danmaku.SegmentConfig)
})
_sym_db.RegisterMessage(SegmentConfig)

DanmakuInfo = _reflection.GeneratedProtocolMessageType('DanmakuInfo', (_message.Message,), {
  'DESCRIPTOR': _DANMAKUINFO,
  '__module__': 'danmaku_pb2'
  # @@protoc_insertion_point(class_scope:bilibili.danmaku.DanmakuInfo)
})
_sym_db.RegisterMessage(DanmakuInfo)

Bullet = _reflection.GeneratedProtocolMessageType('Bullet', (_message.Message,), {
  'DESCRIPTOR': _BULLET,
  '__module__': 'danmaku_pb2'
  # @@protoc_insertion_point(class_scope:bilibili.danmaku.Bullet)
})
_sym_db.RegisterMessage(Bullet)

DanmakuData = _reflection.GeneratedProtocolMessageType('DanmakuData', (_message.Message,), {
  'DESCRIPTOR': _DANMAKUDATA,
  '__module__': 'danmaku_pb2'
  # @@protoc_insertion_point(class_scope:bilibili.danmaku.DanmakuData)
})
_sym_db.RegisterMessage(DanmakuData)

# @@protoc_insertion_point(module_scope)
